import numpy as np 
import matplotlib.pyplot as plt

def sn_random_numbers(shape, antithetic=True, moment_matching=True,fixed_seed=False):
    """
    > Random number generation function
    
    Args:
      shape: the shape of the array of random numbers you want to generate.
      antithetic: If True, then the function generates antithetic variates.
    Defaults to True
      moment_matching: If True, the random numbers will be adjusted to have mean 0
    and variance 1. Defaults to True
      fixed_seed: If True, the random number generator will be seeded with 123.
    This is useful for testing. Defaults to False
    
    Returns:
      a numpy array of random numbers.
    """
    # Setting the seed of the random number generator.
    if fixed_seed:
        rng = np.random.default_rng(123)
    else:
        rng = np.random.default_rng()
    
    # Generating antithetic variates if enabled
    if antithetic:
        ran = rng.standard_normal((shape[0], shape[1], int(shape[2]/2.)))
        ran = np.concatenate((-ran,ran), axis = 2)
    else:
        ran = rng.standard_normal(shape)
    
    # Making the random numbers have mean 0 and variance 1.
    if moment_matching:
        ran = ran - np.mean(ran)
        ran = ran / np.std(ran)
    
    # If the shape of the array is 1, then it returns that element
    if shape[0] == 1:
        ran = ran[0]
        return ran
    else:
        return ran

def set_mpl_style():
    """
    It sets the style of the plots to be generated by matplotlib
    """

    tsize = 12
    tdir = 'in'
    major = 5.0
    minor = 3.0
    style = 'default'
    plt.style.use(style)
    plt.rcParams['text.usetex'] = True
    plt.rcParams['legend.fontsize'] = tsize
    plt.rcParams['xtick.direction'] = tdir
    plt.rcParams['ytick.direction'] = tdir
    plt.rcParams['xtick.major.size'] = major
    plt.rcParams['xtick.minor.size'] = minor
    plt.rcParams['ytick.major.size'] = major
    plt.rcParams['ytick.minor.size'] = minor